### ISSUE TITLE
Support null safety 

### ISSUE THREAD

**Issue by MagicalWater** [justkawal/protect#2]
hello, can it updated to support null safety?

**Comment by justkawal** [comment]
PR is welcome

**Comment by justkawal** [comment]
@MagicalWater Pull Request for null-safety will be available by Mid of Nov

**Comment by lexxxel** [comment]
any news?

**Comment by justkawal** [comment]
@lexxxel
Was on job hunt to earn survival....
For sure before end of January....

**Comment by justkawal** [comment]
@lexxxel @MagicalWater 
Null-safe version of protect is now available: https://pub.dev/packages/protect
`protect: 1.0.0`

Please feel free to re-open the issue in case you find any difficulty.

**Comment by justkawal** [comment]
Drop a 👍🏽 on https://pub.dev/packages/protect if you find it useful.
